# Generated by Django 5.1.5 on 2025-02-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_utilisateur_options_alter_utilisateur_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
