# Generated by Django 5.1.5 on 2025-02-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_utilisateur_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='animaux/'),
        ),
    ]
