# Generated by Django 5.1.5 on 2025-05-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_donation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
