# Generated by Django 5.1.5 on 2025-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescommande',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire (avec remise)'),
        ),
    ]
