# Generated by Django 5.1.5 on 2025-04-09 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('espece', models.CharField(max_length=50)),
                ('race', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Femelle')], max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animaux/')),
                ('disponible_pour_adoption', models.BooleanField(default=False)),
                ('disponible_pour_garde', models.BooleanField(default=False)),
                ('type_garde', models.CharField(choices=[('Temporaire', 'Temporaire'), ('Définitive', 'Définitive')], default='Temporaire', max_length=20)),
                ('date_reservation', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Acceptee', 'Acceptee'), ('Refusee', 'Refusee')], default='En attente', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_adoption', to='animals.animal')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_adoption', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Acceptee', 'Acceptee'), ('Refusee', 'Refusee')], default='En attente', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('type_garde', models.CharField(choices=[('Temporaire', 'Temporaire'), ('Définitive', 'Définitive')], default='Temporaire', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animaux/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_garde', to='animals.animal')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_garde', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvenementMarcheChien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chiens', models.ManyToManyField(related_name='evenements_marche', to='animals.animal')),
            ],
            options={
                'verbose_name': 'Événement de marche',
                'verbose_name_plural': 'Événements de marche',
            },
        ),
       
        migrations.CreateModel(
            name='HistoriqueDemandeAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_precedent', models.CharField(max_length=20)),
                ('statut_nouveau', models.CharField(max_length=20)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiqueadoption', to='animals.animal')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='animals.demandeadoption')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueDemandeGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_precedent', models.CharField(max_length=50)),
                ('statut_nouveau', models.CharField(max_length=50)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('type_garde', models.CharField(choices=[('Temporaire', 'Temporaire'), ('Définitive', 'Définitive'), ('Aucun', 'Aucun')], default='Aucun', max_length=20)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiquegarderie', to='animals.animal')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='animals.demandegarde')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
