# Generated by Django 5.1.5 on 2025-04-08 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_notification_utilisateur_evenementmarchechien_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeEvenementMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Acceptee', 'Acceptee'), ('Refusee', 'Refusee')], default='En attente', max_length=10)),
                ('chiens', models.ManyToManyField(related_name='demandes_marche', to='animals.animal')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='animals.evenementmarchechien')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'événement de marche",
                'verbose_name_plural': "Demandes d'événements de marche",
            },
        ),
    ]
