# Generated by Django 5.1.5 on 2025-04-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_demandeevenementmarche'),
        ('animals', '0003_demandeevenementmarche'),
    ]

    operations = [
    ]
